name: rendering

on:
  push:
    # triggered on tag pushes with tags beginning with either "v" or "dev"
    branches:
      - 'tmp'
  pull_request:
    # also triggered by pull requests on the "dev" branch
    branches:
      - 'tmp'

jobs:
  test-windows:
    runs-on: windows-latest

    env:
      CONDA_ROOT: C:\Miniconda
      MESA_GL_VERSION_OVERRIDE: 4.5
      GALLIUM_DRIVER: llvmpipe
      QT_OPENGL: desktop
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
      PV_DIR: C:\Program Files (x86)\ParaView

    steps:

    - uses: actions/checkout@v2
      name: Checkout ttk-data

    - uses: actions/checkout@v2
      with:
        repository: "pierre-guillou/paraview-ttk"
        ref: "test"
        path: "ttk-paraview"
      name: Checkout TTK-ParaView source code

    - uses: s-weigand/setup-conda@v1

    - name: Remove hosted Python
      shell: bash
      run: |
        rm -rf C:/hostedtoolcache/windows/Python

    - name: Create & configure ParaView build directory
      shell: cmd
      run: |
        call "%VCVARS%"
        cd ttk-paraview
        mkdir build
        cd build
        cmake ^
          -DPARAVIEW_USE_QT=OFF ^
          -DVTK_DEFAULT_RENDER_WINDOW_OFFSCREEN=ON ^
          ..

    - name: Build ParaView
      shell: bash
      run: |
        cd ttk-paraview/build
        cmake --build . --config Release --parallel

    - name: Install ParaView
      shell: bash
      run: |
        cd ttk-paraview/build
        cmake --install .
        echo "$PV_DIR/bin" >> $GITHUB_PATH

    - name: Fetch OpenGL software implementation
      run: |
        Invoke-WebRequest `
          -OutFile mesa3d.7z `
          -Uri https://github.com/pal1000/mesa-dist-win/releases/download/21.0.1/mesa3d-21.0.1-release-mingw.7z

    - name: Install OpenGL software implementation
      shell: bash
      run: |
        which python
        which pvpython
        ldd "$PV_DIR/bin/pvpython.exe"
        mkdir mesa-dist-win
        cd mesa-dist-win
        7z x ../mesa3d.7z
        mv -v x64/* "$PV_DIR/bin"

    - name: Run ttk-data states
      shell: bash
      run: |
        export PYTHONPATH="$PV_DIR/bin/Lib/site-packages:$PYTHONPATH"
        python -X dev tests/run.py -i states/dragon.pvsm || true
        pvpython --help || true
        ls -l tests
