name: rendering

on:
  push:
    # triggered on tag pushes with tags beginning with either "v" or "dev"
    branches:
      - 'tmp'
  pull_request:
    # also triggered by pull requests on the "dev" branch
    branches:
      - 'tmp'

jobs:
  test-windows:
    runs-on: windows-latest

    env:
      CONDA_ROOT: C:\Miniconda
      MESA_GL_VERSION_OVERRIDE: 4.5
      GALLIUM_DRIVER: llvmpipe
      QT_OPENGL: desktop
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
      PV_DIR: C:\Program Files (x86)\ParaView

    steps:

    - uses: actions/checkout@v2
      name: Checkout ttk-data

    - uses: actions/checkout@v2
      with:
        repository: "pierre-guillou/paraview-ttk"
        ref: "test"
        path: "ttk-paraview"
      name: Checkout TTK-ParaView source code

    - name: Remove hosted Python
      shell: bash
      run: |
        rm -rf C:/hostedtoolcache/windows/Python

    - uses: s-weigand/setup-conda@v1

    - name: Install some deps
      shell: bash
      run: |
        conda install -c conda-forge ninja qt

    - name: Create & configure ParaView build directory
      shell: cmd
      run: |
        call "%VCVARS%"
        cd ttk-paraview
        mkdir build
        cd build
        cmake ^
          -DPython3_ROOT_DIR="%CONDA_ROOT%" ^
          -GNinja ^
          ..

    - name: Build ParaView
      shell: cmd
      run: |
        call "%VCVARS%"
        cd ttk-paraview/build
        cmake --build . --config Release --parallel

    - name: Install ParaView
      shell: bash
      run: |
        cd ttk-paraview/build
        cmake --install .
        echo "$PV_DIR/bin" >> $GITHUB_PATH

    - name: Fetch OpenGL software implementation
      run: |
        Invoke-WebRequest `
          -OutFile mesa3d.7z `
          -Uri https://github.com/pal1000/mesa-dist-win/releases/download/21.0.1/mesa3d-21.0.1-release-mingw.7z

    - name: Install OpenGL software implementation
      shell: bash
      run: |
        which python
        which pvpython
        ldd "$PV_DIR/bin/pvpython.exe"
        mkdir mesa-dist-win
        cd mesa-dist-win
        7z x ../mesa3d.7z
        cp x64/* "$CONDA_ROOT"
        cp -v x64/* "$PV_DIR/bin"

    - name: Run ttk-data states
      shell: cmd
      run: |
        call "%VCVARS%"
        set PV_DIR=C:\Program Files (x86)\ParaView
        set PATH=%PATH%;%PV_DIR%\bin
        set PYTHONPATH=%PV_DIR%\bin\Lib\site-packages;%CONDA_ROOT%\Lib
        echo python
        python -X dev -u tests\run.py -i states\dragon.pvsm
        echo ping
        ping -4 -n 35 "">nul
        echo pvpython
        pvpython --help
        dir tests

    - name: Run ttk-data states
      shell: bash
      run: |
        # set environment variables
        export PV_BIN="/c/Program Files (x86)/ParaView/bin"
        export CONDA_ROOT="/c/Miniconda"
        export PATH="$PATH:$PV_BIN:$CONDA_ROOT:$CONDA_ROOT/bin"
        export PYTHONPATH="$PV_BIN/Lib/site-packages:$CONDA_ROOT/Lib"
        # pure python
        python -X dev -u tests/run.py -i states/dragon.pvsm || true
        sleep 2
        ls -l tests
        # pvpython
        pvpython.exe -X dev -u tests/run.py -i states/dragon.pvsm || true
        sleep 2
        ls -l tests
